### ISSUE TITLE
Unable to build on ubuntu 20.04

### ISSUE THREAD

**Issue by AaronKaa** [gnustep/corebase#19] opened 2020-08-16 22:15 UTC
Have followed the build guide at : http://wiki.gnustep.org/index.php/Building_GNUstep_under_Debian_FreeBSD - without corebase I can still build apps, can build and run GWorkspace but when trying to build codebase I get this during build : 

checking for library containing objc_getClass... no
configure: error: Objective-C library not found!  Use --without-objc-bridge to explicitly disable the toll-free bridge or install the Objective-C library.

Im using clang-8, ubuntu 20.04 

I don't get this during any other build

**Comment by AaronKaa** [comment] 2020-08-17 21:13
When corebase checks for objc it tries to find a lib containing objc_getClass but this isnt checked in the config for base or gui, is this an old check that can be removed ?

**Comment by cburgmer** [comment] 2020-10-17 16:51
If it helps, I've successfully built it against ubuntu 20.10: https://github.com/cburgmer/json-path-comparison/blob/master/src/installObjectiveC.sh

**Comment by digital-pers0n** [comment] 2020-11-10 14:56
I had the same problem when building it on Debian. The problem is that corebase can't find libobjc if it was installed from git. I've managed to fix this by manually adding paths to libobjc and its headers into CFLAGS and LDFLAGS via -L and -I  clang flags

**Comment by stefanbidi** [comment] 2022-09-11 19:00
I apologize for not addressing this issue sooner, I have not been able to provide much time to GNUstep in the last few years.

That being said, I do not understand the problem. CoreBase's configure script checks for libobjc and libobjc2 directly because it needs functions explicitly defined in one of those two libraries. By default, configure only checks libraries in `/lib` and `/usr/lib`. If a library was installed in `/usr/local`, then you must add the path using `CFLAGS=-I/usr/local/include` and `LDFLAGS=-l/usr/local/lib`.

Since this is the default behavior for autoconf and not something in CoreBase, I will close this issue. The issue can be reopened if not what was described above.

**Closed as completed by stefanbidi** 2022-09-11 19:00 UTC
